#================================ Workflow =================================================#
#                                                                                           #
# This flow used to build docker image for github-readme-stats and push to Docker Hub       #
#                                                                                           #
# Author: Dung Pham                                                                         #
# Site: https://devopslite.com                                                              #
#===========================================================================================#

name: = BUILD IMAGE github-readme-stats =

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

### Ensures that only one CI task per branch/environment will run at a time ###
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#############################################################################
#=============================BUILD DOCKER IMAGE============================#
#############################################################################

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push docker image
        shell: bash
        env:
          REGISTRY: dungpham91
          REPOSITORY: github-readme-stats
        run: |
          TAG_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | sed "s/ //g")
          echo ${TAG_VERSION}

          docker build \
            -t $REGISTRY/$REPOSITORY:${TAG_VERSION} \
            -t $REGISTRY/$REPOSITORY:latest .

          echo "Pushing image to ECR..."
          docker push $REGISTRY/$REPOSITORY --all-tags
